PrintComment: ThisGoesHere cleans up the Krumpac configs to let them be regenerated and delete outdated files and mods
DeleteFolder:
- config\KeyManager\
MoveFolder:
- From: plugins/Krumpac-Krumpacs_Biome_Clutter_2/Krumpacs Biome Clutter
  To: plugins/
- From: plugins/Krumpac-Krumpacs_Biome_Clutter/Krumpacs Biome Clutter
  To: plugins/